config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :horses, only: %i[index show] do
    resources :bookings, only: :create
  end

  namespace :owner do
    resources :horses
    resources :bookings, except: %i[index show new create edit update destroy] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  resource :profile, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :horse
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
  validates :status, presence: true, inclusion: { in: ['pending', 'approved', 'declined'] }
end

app/models/horse.rb
class Horse < ApplicationRecord
  belongs_to :user
  has_many :bookings

  validates :name, presence: true
  validates :price, presence: true

  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :horses

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_horse, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.horse = @horse
    @booking.user = current_user
    @booking.status = "pending"

    date1 = @booking.start_date
    date2 = @booking.end_date
    nb_jour = (date2 - date1).to_i

    if nb_jour > 0
      @booking.total_price = nb_jour * @horse.price
      if @booking.save
        flash[:notice] = "Votre demande de location a été envoyée"
        redirect_to horse_path(@booking.horse_id)
      else
        flash.now[:alert] = "Votre demande de location n'a pas pu être envoyée"
        render "horses/show", status: :unprocessable_entity
      end
    else
      flash.now[:alert] = "Demande de location trop courte !"
      render "horses/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

  def set_horse
    @horse = Horse.find(params[:horse_id])
  end
end

app/controllers/horses/bookings_controller.rb
class Horse::BookingsController < ApplicationController
  before_action :set_horse, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.horse = @horse
    @booking.user = current_user
    @booking.status = "pending"

    date1 = Date.new(@booking.start_date)
    date2 = Date.new(@booking.end_date)
    nb_jour = (date2 - date1).to_i

    if nb_jour > 0
      @booking.total_price = nb_jour * @horse.price
      if @booking.save
        redirect_to horse_path(@booking.horse_id)
      else
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

  def set_horse
    @horse = Horse.find(params[:horse_id])
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def show
    @horse = Horse.find(params[:id])
    @booking = Booking.new
  end

  def index
    @horses = Horse.all
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    @user = current_user
    @bookings = @user.bookings.where(status: %i[approved declined])
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "approved")
    redirect_to profile_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to profile_path
  end
end

app/controllers/owner/horses_controller.rb
class Owner::HorsesController < ApplicationController
  def new
    @horse = Horse.new
  end

  def create
    @horse = Horse.new(horse_params)
    @horse.user = current_user
    if @horse.save
      redirect_to owner_horses_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @horses = current_user.horses
  end

  private

  def horse_params
    params.require(:horse).permit(:name, :breed, :specialty, :city, :age, :sex, :price, :photo, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @horses = Horse.first(3)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
    @user_bookings = current_user.bookings
    @booking_received = Booking.where(horse_id: current_user.horses.pluck(:id))
    @booking = @user.bookings.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/horses/index.html.erb
<div class="container">
  <div class="mt-5 offset-lg-1">
    <h1>Nos chevaux 🐎</h1>
    <h3>Louer un cheval <span data-controller="typed-js"></span></h3>
  </div>
  <div class="horse-card-grid mx-auto my-5">
      <% @horses.each do |horse| %>
        <a href="<%= horse_path(horse) %>" class="horse-card">
          <%= cl_image_tag horse.photo.key, class: "img-fluid" %>
            <div class="horse-card-details p-4">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h3><%= horse.name.upcase %></h3>
                  <div class="breed">
                    🐴 <%= horse.breed.upcase %>
                  </div>
                </div>
                <div class="price">
                  <%= horse.price %>€ / J
                </div>
              </div>
          </div>
        </a>
      <% end %>
  </div>
</div>

app/views/horses/show.html.erb
<div class="card-show">
  <div class="show-vertical">

    <div class="card-format">
      <%= image_tag "fondback.jpg" %>
        <div id="cardformatpagging">
          <h1 class="name-title"><strong><%= @horse.name %></strong> </h1>
          <div class="paragraphe">
            <h3 class="sous-title"><strong style="color: black;"><%= "#{@horse.breed}" %></strong><%=" | #{@horse.specialty} |" %></h3>
              <ul class="orgalist" id="listicone">
                <li><i class="fa-solid fa-cake-candles fa-xl fontawseomeform"></i><%="   #{@horse.age}"%>ans</li>
                <li><i class="fa-solid fa-user fa-xl fontawseomeform"></i><%="   #{@horse.user.name}"%></li>
                <li><i class="fa-solid fa-venus-mars fa-xl"></i> <%="     #{@horse.sex}"%></li>
                <li><i class="fa-solid fa-city fa-xl"></i> <%="    #{@horse.city}"%></li>
              </ul>
          </div>
        </div>

        <div class="separation"></div>

        <div class="name-title-description">
          <h1 class="name-title-describ"><strong><%= "Description" %></strong> </h1>
          <p class="paragraphedescrib"><%= "#{@horse.description}" %></p>
        </div>
    </div>

    <div class="card-format2" data-controller="price" data-price="<%= @horse.price %>">
      <%= image_tag "fondback.jpg" %>
         <div id="cardformat2pagging">
            <h1 class="name-title"><strong>Réservation</strong></h1>
            <%= simple_form_for [@horse, @booking] do |f| %>
              <div class="container">
                <div class="row">
                  <%= f.input :start_date, as: :date, label:"Date de départ", placeholder:"17/03/2023", html5: true, input_html: { data: { "price-target": "startDate", action: "change->price#result" } } %>
                  <%= f.input :end_date, as: :date, label:"Date de retour", placeholder:"23/03/2023", html5: true, input_html: { data: { "price-target": "endDate", action: "change->price#result" } } %>
                </div>
                <div class="row">
                  <div class="col-6 ">
                    <p ><strong><%= "#{@horse.price}€"%></strong><%= "/ Jour" %></p>
                    <div id="margin0">
                      <h2 data-price-target="priceTag">--€</h2>
                    </div>
                  </div>
                  <div class="col-6  d-flex justify-content-end">
                    <%= f.submit class:"btn btn-pmured mt-4", value:"Réserver"%>
                  </div>
                </div>
                <% end %>
              </div>
          </div>
    </div>
  </div>


  <div class="format">
    <%= cl_image_tag @horse.photo.key, class:"img-cheval" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeraCheval</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/owner/horses/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center col-lg-10 offset-lg-1 mt-5">
    <div>
      <h1>L'écurie 🏇</h1>
      <h3>Voici les chevaux que vous avez enregistré chez nous...</h3>
    </div>
    <%= link_to "AJOUTER UN CHEVAL", new_owner_horse_path, class: 'btn-pmured align-self-center' %>
  </div>
  <%= render 'shared/horse_card_grid' %>
</div>

app/views/owner/horses/new.html.erb
<div class="small-form mt-5">
  <h1 id="form_title">AJOUTER UN CHEVAL</h1>
    <%= simple_form_for @horse, url: owner_horses_path do |f| %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-4">
        <%= f.input :name, label:"Nom", placeholder:"Hugo"  %>
      </div>
      <div class="col-2">
        <%= f.input :age, label:"Age", placeholder:"11"  %>
      </div>
      <div class="col-6">
        <%= f.input :photo, as: :file %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-6">
        <%= f.input :breed, label:"Race", placeholder:"Pur-sang"  %>
      </div>
      <div class="col-6">
        <%= f.input :specialty, label:"Specialitée", placeholder:"Promenade / Trait ..."%>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-4">
        <%= f.input :city, label:"Localisation", placeholder:"Ville"%>
      </div>

      <div class="col-4">
        <%= f.input :sex, collection:["Mâle", "Femelle"], label:"Sexe", selected:"Mâle" %>
      </div>

      <div class="col-4">
        <%= f.input :price, label:"Prix", placeholder:"€"%>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <%= f.input :description %>
    </div>
  </div>
  <div class="container">
    <div class="row">
        <%= f.submit class:"btn btn-pmured mt-4 pull-right"%>
    </div>
    <div class="row text-center mt-3">
      <%= link_to "Retour à l'écurie", owner_horses_path, class: "pmured-link" %>
    </div>
  </div>
</div>
<% end %>

app/views/pages/home.html.erb
<div id="homeBanner" class="banner" style="background-image: url(<%= image_path('image-banner.png') %>);">
    <h1>FeraCheval</h1>
    <h2>Le cheval c'est trop génial</h2>
    <%= link_to "LOUER UN CHEVAL", horses_path, class: 'btn-pmured mb-5 mt-5 d-inline-block' %>
</div>

<div class="container">
  <div class="mt-5 offset-lg-1">
    <h2 class="h1">Chevaux vedettes 🐎</h1>
    <h3>La sélection des chevaux les plus prisés</h2>
  </div>
  <%= render 'shared/horse_card_grid' %>
</div>

app/views/profiles/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8 mt-4">
      <h1 class>Demandes de réservation</h1>
      <% @user.bookings.order(start_date: :desc).each do |booking| %>
        <div class="booking-card d-flex mb-4 mt-3">
          <%= cl_image_tag booking.horse.photo.key, class: "img-fluid" %>
          <div class="d-flex w-100 justify-content-around align-items-center">
            <h3> <%=booking.horse.name%></h3>
            <p><i class="fa-regular fa-calendar text-pmured"></i> <%= booking.start_date.strftime("%d/%m/%Y") %> - <%= booking.end_date.strftime("%d/%m/%Y") %></p>
            <p class="h5 text-pmured"><%= booking.total_price%>€</p>
            <% if current_user == booking.horse.user %>
              <% if booking.status == "pending" %>
            <div class="d-flex">
              <%= link_to "Accepter", accept_owner_booking_path(booking), data: { turbo_method: :patch }, class: "pmugreen-link mr-3" %>
              <div class="mx-3"></div>
              <%= link_to "Refuser", decline_owner_booking_path(booking), data: { turbo_method: :patch }, class: "pmured-link" %>
            </div>
              <% elsif booking.status == "approved"  %>
                <i class="fa-solid fa-square-check"></i>
              <% else %>
	              <i class="fa-solid fa-xmark"></i>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4 mt-4">
      <div class="mx-3">
        <h1 class="mx-1">Mes informations</h1>
      </div>
      <div class="container d-flex justify-content-center align-items-center">
        <div class="card mt-2">
          <div class="text-center mt-4">
            <%= cl_image_tag @user.photo.key, class: "avatar-large", width: "80" %>
          </div>
          <div class="text-center mt-4">
            <h4 class="mb-0"><%= @user.name%> </h4>
            <p><%= link_to "Voir mes cheveaux", owner_horses_path, class: "pmured-link", class: "btn btn-pmured mt-3"%></p>
            <div class="d-flex justify-content-between align-items-center px-4">
              <div class="stats">
                <h6 class="mb-0">Nombre de cheveaux</h6>
                <span><%= @user.horse_ids.count %></span>
              </div>
              <div class="stats m-4">
                <h6 class="mb-0">Mes réservations</h6>
                <span><%=@user.bookings.count %> </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <h1 class="mt-5">Mes reservations précendentes</h1>
  <div class="horse-card-grid mx-auto my-5">
      <% @booking_received.each do |booking| %>
        <a href="<%= horse_path(booking.horse) %>" class="horse-card">
          <%= cl_image_tag booking.horse.photo.key, class: "img-fluid" %>
            <div class="horse-card-details p-4">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <h3><strong><%= booking.horse.name %></strong></h3>
                  <div class="breed">
                    🐴 <%= booking.horse.breed %>
                  </div>
                </div>
                <div class="date">
                  <%= booking.start_date %>
                </div>
                <div class="price">
                  <%= booking.total_price %>€
                </div>
              </div>
          </div>
        </a>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_horse_card_grid.html.erb
<div class="horse-card-grid mx-auto my-5">
  <% @horses.each do |horse| %>
    <a href="<%= horse_path(horse) %>" class="horse-card">
      <%= cl_image_tag horse.photo.key, class: "img-fluid" %>
        <div class="horse-card-details p-4">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <h3><%= horse.name.upcase %></h3>
              <div class="breed">
                🐴 <%= horse.breed.upcase %>
              </div>
            </div>
            <div class="price">
              <%= horse.price %>€ / J
            </div>
          </div>
      </div>
    </a>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-success px-3">
  <a class="navbar-brand logo-font" href="/">
    <%= image_tag('logo.jpg', size: '50')%>
    FeraCheval
  </a>
  <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
    <li class="nav-item mx-2">
      <%= link_to "Louer un cheval", horses_path, class: "nav-link-pmu" %>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item mx-2">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar current-user", data: { bs_toggle: "dropdown" } %>
          <ul class="dropdown-menu dropdown-menu-end p-3">
            <li><%= link_to "Profile", profile_path, class: "pmured-link text-decoration-none" %></li>
            <li><%= link_to "Mes chevaux", owner_horses_path, class: "pmured-link text-decoration-none" %></li>
            <li><%= link_to "Se déconnecter", destroy_user_session_path, data: { "turbo-method": :delete }, class: "pmured-link text-decoration-none" %></li>
          </ul>
        </div>
      </li>
    <% else %>
      <li class="nav-item mx-2">
        <div class="dropdown">
          <%= image_tag "https://www.startpage.com/av/proxy-image?piurl=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F008%2F442%2F086%2Foriginal%2Fillustration-of-human-icon-user-symbol-icon-modern-design-on-blank-background-free-vector.jpg&sp=1677839053T6f9d7dd49c983a9bfbd3e4afa60bf46add84e538686d041ebd3ab9ad23bc5b40", class: "avatar current-user", data: { bs_toggle: "dropdown" } %>
          <ul class="dropdown-menu dropdown-menu-end p-3">
            <li><%= link_to "Se connecter", new_user_session_path, class: "pmured-link text-decoration-none" %></li>
            <li><%= link_to "S'inscrire", new_user_registration_path, class: "pmured-link text-decoration-none" %></li>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
</nav>